# This is a automated publishing workflow.

name: continious publish

on:
 push:
    branches:
    - test2
  release:
    types:
    - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
     
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    
    - name: Install NPM packages
      run: npm install
      
    - name: Compile code
      run: npm run compile
      
    - name: Run tests
      uses: GabrielBB/xvfb-action@v1.2
      with:
        run: npm test
        
    - name: Publish
      run: npm run deploy
      env:
        PUBLISHER_TOKEN: $
